name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Buildx the Docker image
        run: |
          docker buildx create --use && \
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --file ltsp-base/Dockerfile \
            --output "type=image,push=false" \
            --tag georgiapipeline/ltsp-base:latest .
