name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker buildx create --use && docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file Dockerfile --tag georgiapipeline/ltsp-base:latest .
      working-directory: ltsp-base
