name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: actions/checkout@v2
      - name: Build the ltsp-base
        run: |
          docker build \
            --file DockerfileArm64 \
            --output "type=image,push=false" \
            --tag georgiapipeline/ltsp-base:arm64-latest .
        working-directory: ltsp-base
      - name: Push build ltsp-base
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} \
          docker push tag georgiapipeline/ltsp-base:arm64-latest
        working-directory: ltsp-base


