name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker
        run: docker login --username $USERNAME --password $PASSWORD
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the ltsp-base
        run: |
          docker build \
            --file DockerfileArm64 \
            --output "type=image,push=false" \
            --tag georgiapipeline/ltsp-base:arm64-latest .
        working-directory: ltsp-base

      - name: Push build ltsp-base
        run: docker push georgiapipeline/ltsp-base:arm64-latest
        working-directory: ltsp-base

#      - name: Build the ltsp-basesystem
#        run: |
#          docker build \
#            --file DockerfileArm64 \
#            --output "type=image,push=false" \
#            --tag georgiapipeline/ltsp-basesystem:arm64-latest .
#        working-directory: ltsp-basesystem
#
#      - name: Push build ltsp-basesystem
#        run: docker push georgiapipeline/ltsp-basesystem:arm64-latest
#        working-directory: ltsp-basesystem

